# 스칼라 실습

# 벡터 실습

In [1]:
a = [1,2,3]
print(a)

[1, 2, 3]


In [2]:
b = [3,6,9]
print(b)

[3, 6, 9]


In [3]:
c = []

for i in range(0, len(a)):
    val = a[i] + b[i]
    c.append(val)
print(c)

[4, 8, 12]


# 쇼핑몰 데이터를 활용한 실습 with pandas library

In [4]:
import pandas as pd

In [5]:
import glob

In [6]:
path = glob.glob('data/*.csv')
path

['data\\mall_customer.csv',
 'data\\PokemonDb.csv',
 'data\\star_classification.csv',
 'data\\StudentsPerformance.csv',
 'data\\wine.csv',
 'data\\WineQT.csv']

In [7]:
df = pd.read_csv(path[0])
df

CustomerID  Gender  Age  Annual Income  Spending Score
0             1       1   19             15              39
1             2       1   21             15              81
2             3       2   20             16               6
3             4       2   23             16              77
4             5       2   31             17              40
..          ...     ...  ...            ...             ...
195         196       2   35            120              79
196         197       2   45            126              28
197         198       1   32            126              74
198         199       1   32            137              18
199         200       1   30            137              83

[200 rows x 5 columns]

#### `스칼라연산`

In [14]:
df.iloc[2,2]

20

In [15]:
df.iloc[3,2]

23

In [17]:
df.iloc[2,2] + df.iloc[3,2]

43

#### `벡터연산`

In [19]:
df['Age']

0      19
1      21
2      20
3      23
4      31
       ..
195    35
196    45
197    32
198    32
199    30
Name: Age, Length: 200, dtype: int64

In [20]:
df['Annual Income']

0       15
1       15
2       16
3       16
4       17
      ... 
195    120
196    126
197    126
198    137
199    137
Name: Annual Income, Length: 200, dtype: int64

In [21]:
df['Age'] + df['Annual Income']

0       34
1       36
2       36
3       39
4       48
      ... 
195    155
196    171
197    158
198    169
199    167
Length: 200, dtype: int64

In [22]:
import numpy as np

In [25]:
df

CustomerID  Gender  Age  Annual Income  Spending Score
0             1       1   19             15              39
1             2       1   21             15              81
2             3       2   20             16               6
3             4       2   23             16              77
4             5       2   31             17              40
..          ...     ...  ...            ...             ...
195         196       2   35            120              79
196         197       2   45            126              28
197         198       1   32            126              74
198         199       1   32            137              18
199         200       1   30            137              83

[200 rows x 5 columns]

In [24]:
df_t = np.transpose(df)
df_t

0    1    2    3    4    5    6    7    8    9    ...  190  \
CustomerID        1    2    3    4    5    6    7    8    9   10  ...  191   
Gender            1    1    2    2    2    2    2    2    1    2  ...    2   
Age              19   21   20   23   31   22   35   23   64   30  ...   34   
Annual Income    15   15   16   16   17   17   18   18   19   19  ...  103   
Spending Score   39   81    6   77   40   76    6   94    3   72  ...   23   

                191  192  193  194  195  196  197  198  199  
CustomerID      192  193  194  195  196  197  198  199  200  
Gender            2    1    2    2    2    2    1    1    1  
Age              32   33   38   47   35   45   32   32   30  
Annual Income   103  113  113  120  120  126  126  137  137  
Spending Score   69    8   91   16   79   28   74   18   83  

[5 rows x 200 columns]

In [26]:
df_t.dot(df)

CustomerID  Gender     Age  Annual Income  Spending Score
CustomerID         2686700   31027  776579        1512980         1013135
Gender               31027     536   12037          18748           15811
Age                 776579   12037  340696         469646          366564
Annual Income      1512980   18748  469646         870780          609359
Spending Score     1013135   15811  366564         609359          636712

In [27]:
df.dot(df_t)

0     1     2      3     4      5     6      7     8      9    ...  \
0    2109  3786   859   3686  2411   3645  1178   4383  1628   3675  ...   
1    3786  7232  1154   6970  4158   6887  1507   8385  1891   6769  ...   
2     859  1154   705   1194  1151   1190  1049   1340  1631   1370  ...   
3    3686  6970  1194   6734  4089   6658  1587   8091  2045   6582  ...   
4    2411  4158  1151   4089  2879   4045  1670   4823  2474   4187  ...   
..    ...   ...   ...    ...   ...    ...   ...    ...   ...    ...  ...   
195  5744  9328  3686   9596  7269   9994  5235  11963  6523  10982  ...   
196  4036  5499  3679   5999  5646   6446  5394   7515  7133   7734  ...   
197  5583  8953  3696   9244  7086   9660  5220  11546  6447  10664  ...   
198  3565  4584  3539   5112  5038   5597  5089   6488  6497   6851  ...   
199  6063  9809  3892  10075  7581  10499  5416  12560  6573  11481  ...   

       190    191    192    193    194    195    196    197    198    199  
0     3281   5038   2828   6162   3514   5744   4036   5583   3565   6063  
1     4506   8192   3423  10254   4475   9328   5499   8953   4584   9809  
2     3043   3282   3097   3700   3545   3686   3679   3696   3539   3892  
3     4969   8469   3957  10469   5017   9596   5999   9244   5112  10075  
4     4684   6467   4231   7713   5116   7269   5646   7086   5038   7581  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
195  52807  56567  53177  60107  55533  60286  57523  60896  57988  63249  
196  52783  54178  53970  56718  56102  57523  57498  58396  58411  60338  
197  53588  57126  54101  60602  56420  60896  58396  61581  59021  63965  
198  53624  54587  55089  56943  57039  57988  58411  59021  59719  61024  
199  55242  59200  55736  62976  58180  63249  60338  63965  61024  66559  

[200 rows x 200 columns]

In [29]:
df = pd.read_csv(path[5])
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [32]:
density = df['density']
pH = df['pH']

In [34]:
import numpy as np

res = np.inner(density, pH)
print(res)

3771.9947732


In [36]:
sub_df = pd.read_csv(path[2])
sub_df

Unnamed: 0        obj_ID       alpha      delta         u         g  \
0               0  1.237661e+18  135.689107  32.494632  23.87882  22.27530   
1               1  1.237665e+18  144.826101  31.274185  24.77759  22.83188   
2               2  1.237661e+18  142.188790  35.582444  25.26307  22.66389   
3               3  1.237663e+18  338.741038  -0.402828  22.13682  23.77656   
4               4  1.237680e+18  345.282593  21.183866  19.43718  17.58028   
...           ...           ...         ...        ...       ...       ...   
99995       99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586   
99996       99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628   
99997       99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997   
99998       99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757   
99999       99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745   

              r         i         z  run_ID  rerun_ID  cam_col  field_ID  \
0      20.39501  19.16573  18.79371    3606       301        2        79   
1      22.58444  21.16812  21.61427    4518       301        5       119   
2      20.60976  19.34857  18.94827    3606       301        2       120   
3      21.61162  20.50454  19.25010    4192       301        3       214   
4      16.49747  15.97711  15.54461    8102       301        3       137   
...         ...       ...       ...     ...       ...      ...       ...   
99995  21.90404  21.30548  20.73569    7778       301        2       581   
99996  20.45003  19.75759  19.41526    7917       301        1       289   
99997  18.20428  17.69034  17.35221    5314       301        4       308   
99998  19.91386  19.07254  18.62482    3650       301        4       131   
99999  20.60115  20.00959  19.28075    3650       301        4        60   

        spec_obj_ID  class  redshift  plate    MJD  fiber_ID  
0      6.543777e+18      0  0.634794   5812  56354       171  
1      1.176014e+19      0  0.779136  10445  58158       427  
2      5.152200e+18      0  0.644195   4576  55592       299  
3      1.030107e+19      0  0.932346   9149  58039       775  
4      6.891865e+18      0  0.116123   6121  56187       842  
...             ...    ...       ...    ...    ...       ...  
99995  1.055431e+19      0  0.000000   9374  57749       438  
99996  8.586351e+18      0  0.404895   7626  56934       866  
99997  3.112008e+18      0  0.143366   2764  54535        74  
99998  7.601080e+18      0  0.455040   6751  56368       470  
99999  8.343152e+18      0  0.542944   7410  57104       851  

[100000 rows x 19 columns]

In [39]:
sub_df = df[['u','g','r','i','z']]

In [40]:
#전치행렬
sub_df_t = np.transpose(sub_df)

In [41]:
sub_df_t

0         1         2         3         4         5         6      \
u  23.87882  24.77759  25.26307  22.13682  19.43718  23.48827  21.46973   
g  22.27530  22.83188  22.66389  23.77656  17.58028  23.33776  21.17624   
r  20.39501  22.58444  20.60976  21.61162  16.49747  21.32195  20.92829   
i  19.16573  21.16812  19.34857  20.50454  15.97711  20.25615  20.60826   
z  18.79371  21.61427  18.94827  19.25010  15.54461  19.54544  20.42573   

      7         8         9      ...     99990     99991     99992     99993  \
u  22.24979  24.40286  21.74669  ...  23.79655  26.22899  25.82234  23.13172   
g  22.02172  22.35669  20.03493  ...  22.41332  21.84820  24.02722  23.18506   
r  20.34126  20.61032  19.17553  ...  20.36012  20.47138  21.43137  21.52854   
i  19.48794  19.46490  18.81823  ...  19.33964  19.60049  20.13085  20.26975   
z  18.84999  18.95852  18.65422  ...  18.74413  18.94726  19.66464  20.11383   

      99994     99995     99996     99997     99998     99999  
u  20.96526  22.16759  22.69118  21.16916  25.35039  22.62171  
g  19.81625  22.97586  22.38628  19.26997  21.63757  21.79745  
r  19.34186  21.90404  20.45003  18.20428  19.91386  20.60115  
i  19.14711  21.30548  19.75759  17.69034  19.07254  20.00959  
z  19.05790  20.73569  19.41526  17.35221  18.62482  19.28075  

[5 rows x 100000 columns]

In [42]:
cov_df = sub_df_t.dot(sub_df)

In [44]:
#e가 고윳값, v는 고유벡터  / 2개가 나오게 무조건 걸어놓음
# 고윳값 분해 : eig = eigenvalue decomposition , 유니크 
e, v = np.linalg.eig(cov_df)
e
#고윳값이 큰 순서대로 나온다 

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [45]:
v

array([[-0.5733491 ,  0.0909501 , -0.67895384,  0.44905829,  0.01916291],
       [-0.56012813,  0.14008024, -0.03231131, -0.78254068, -0.23069477],
       [-0.18000134, -0.69174032, -0.04794331, -0.19084663,  0.67109898],
       [-0.17473995, -0.67196189,  0.16814737,  0.19588892, -0.67177911],
       [-0.54276399,  0.20510523,  0.71232406,  0.33343941,  0.21154596]])

In [47]:
# 특이값  //// 특이값 분해 : svd - singular value decomposition
U, S, Vt = np.linalg.svd(cov_df)
U

array([[-0.5733491 , -0.0909501 ,  0.67895384,  0.44905829, -0.01916291],
       [-0.56012813, -0.14008024,  0.03231131, -0.78254068,  0.23069477],
       [-0.18000134,  0.69174032,  0.04794331, -0.19084663, -0.67109898],
       [-0.17473995,  0.67196189, -0.16814737,  0.19588892,  0.67177911],
       [-0.54276399, -0.20510523, -0.71232406,  0.33343941, -0.21154596]])

In [48]:
S
#특이값이 큰 순서대로 나온다 

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [49]:
#ㅍ 전치 
Vt

array([[-0.5733491 , -0.56012813, -0.18000134, -0.17473995, -0.54276399],
       [-0.0909501 , -0.14008024,  0.69174032,  0.67196189, -0.20510523],
       [ 0.67895384,  0.03231131,  0.04794331, -0.16814737, -0.71232406],
       [ 0.44905829, -0.78254068, -0.19084663,  0.19588892,  0.33343941],
       [-0.01916291,  0.23069477, -0.67109898,  0.67177911, -0.21154596]])